spring.application.name=StanveeRento

#db url for render 

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.batch_size=100
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true
spring.datasource.hikari.data-source-properties.prepareThreshold=0
spring.datasource.hikari.data-source-properties.preparedStatementCacheQueries=0
spring.datasource.hikari.data-source-properties.preparedStatementCacheSize=0
spring.datasource.hikari.data-source-properties.useServerPrepStmts=false
spring.datasource.hikari.data-source-properties.cachePrepStmts=false


spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.connection-timeout=600000
spring.datasource.hikari.validation-timeout=5000
spring.datasource.hikari.keepalive-time=150000





#spring.datasource.url=${DB_URL}
#spring.datasource.username=${DB_USER}
#spring.datasource.password=${DB_PASSWORD}



spring.datasource.url=jdbc:postgresql://aws-0-ap-south-1.pooler.supabase.com:5432/postgres?sslmode=require  
spring.datasource.username=postgres.pdhqkittihpevabwjyze
spring.datasource.password=Stanvee@1337



# JWT
security.jwt.secret=U3RhbndlZVJlbnRvU3VwZXJBZG1pbkp3dFNlY3JldEtleTIwMjZMb25nVmFsdWU=
security.jwt.access-expiration-ms=3600000
security.jwt.refresh-expiration-ms=604800000

#spring.datasource.url=${DB_URL}
#spring.datasource.username=${DB_USER}
#spring.datasource.password=${DB_PASSWORD}
## Replace with your actual Render URL
#
#app.base-url=https:https://stanveeshopbackend.onrender.com
#airpay.cors.allowedOrigins=http://localhost:3000,http://localhost:8080,http://127.0.0.1:5501,https://shop.stanvee.com
#airpay.frontendBaseUrl=https://shop.stanvee.com

